### ISSUE TITLE
Can't build on ubuntu 18.04

### ISSUE THREAD

**Issue by s416058** [zpchavez/Bartizan#23]
I tried build with xbuild but I get this error:

```
Classes/Patched/MyMatchSettings.cs(20,24): error CS1501: No overload for method 'PlayerGoals' takes 7 arguments
Classes/Patched/MyVersusPlayerMatchResults.cs(17,9): error CS1729: 'VersusPlayerMatchResults' does not contain a constructor that takes 7 arguments
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/mnt/home/kryspin/Pobrane/Github/Bartizan/Mod/Mod.csproj".-- FAILED
		Done building project "/mnt/home/kryspin/Pobrane/Github/Bartizan/Mod/Mod.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/mnt/home/kryspin/Pobrane/Github/Bartizan/Bartizan.sln".-- FAILED
Done building project "/mnt/home/kryspin/Pobrane/Github/Bartizan/Bartizan.sln".-- FAILED

Build FAILED.
Errors:

/mnt/home/kryspin/Pobrane/Github/Bartizan/Bartizan.sln (default targets) ->
(Build target) ->
/mnt/home/kryspin/Pobrane/Github/Bartizan/Mod/Mod.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Classes/Patched/MyMatchSettings.cs(20,24): error CS1501: No overload for method 'PlayerGoals' takes 7 arguments
	Classes/Patched/MyVersusPlayerMatchResults.cs(17,9): error CS1729: 'VersusPlayerMatchResults' does not contain a constructor that takes 7 arguments

	 0 Warning(s)
	 2 Error(s)

Time Elapsed 00:00:01.8464010
```

mono --version :

```
Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:20:38 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)
```

[build.log](https://github.com/zpchavez/Bartizan/files/2613068/build.log)

**Comment by zpchavez** [comment]
Wow. I _just_ noticed this issue. That error sounds like you are trying to patch the standard 4-player version of the game. My fork only works with the 8-player mod.

**Comment by zpchavez** [comment]
The original poster has no doubt moved on with their life, but just for the record I've added support for 4-player back in. You just need to undefine the preprocessor constant EIGHT_PLAYER. Eventually I'll make builds of the patcher so people don't need to fiddle with visual studio.

**Comment by zpchavez** [comment]
And if anyone is reading _this_ you can now switch between 4 and 8 player using the provided build configurations, or just download builds if you're not on Linux
